# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keithleyMainWindow.ui'
#
# Created: Tue Jul 02 11:44:03 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_keithleyOnlyWindow(object):
    def setupUi(self, keithleyOnlyWindow):
        keithleyOnlyWindow.setObjectName(_fromUtf8("keithleyOnlyWindow"))
        keithleyOnlyWindow.resize(820, 505)
        self.centralwidget = QtGui.QWidget(keithleyOnlyWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.grbSweepType = QtGui.QGroupBox(self.centralwidget)
        self.grbSweepType.setGeometry(QtCore.QRect(20, 280, 351, 51))
        self.grbSweepType.setObjectName(_fromUtf8("grbSweepType"))
        self.rdoLinear = QtGui.QRadioButton(self.grbSweepType)
        self.rdoLinear.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rdoLinear.setObjectName(_fromUtf8("rdoLinear"))
        self.rdoLog = QtGui.QRadioButton(self.grbSweepType)
        self.rdoLog.setGeometry(QtCore.QRect(110, 20, 131, 17))
        self.rdoLog.setObjectName(_fromUtf8("rdoLog"))
        self.rdoDC = QtGui.QRadioButton(self.grbSweepType)
        self.rdoDC.setGeometry(QtCore.QRect(240, 20, 82, 17))
        self.rdoDC.setObjectName(_fromUtf8("rdoDC"))
        self.grbSweepParam = QtGui.QGroupBox(self.centralwidget)
        self.grbSweepParam.setGeometry(QtCore.QRect(20, 340, 351, 151))
        self.grbSweepParam.setObjectName(_fromUtf8("grbSweepParam"))
        self.lblSWBias = QtGui.QLabel(self.grbSweepParam)
        self.lblSWBias.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.lblSWBias.setObjectName(_fromUtf8("lblSWBias"))
        self.lblSWBiasRange = QtGui.QLabel(self.grbSweepParam)
        self.lblSWBiasRange.setGeometry(QtCore.QRect(180, 30, 91, 16))
        self.lblSWBiasRange.setObjectName(_fromUtf8("lblSWBiasRange"))
        self.lblSWStart = QtGui.QLabel(self.grbSweepParam)
        self.lblSWStart.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.lblSWStart.setObjectName(_fromUtf8("lblSWStart"))
        self.lblSWStop = QtGui.QLabel(self.grbSweepParam)
        self.lblSWStop.setGeometry(QtCore.QRect(180, 60, 46, 13))
        self.lblSWStop.setObjectName(_fromUtf8("lblSWStop"))
        self.lblSWStep = QtGui.QLabel(self.grbSweepParam)
        self.lblSWStep.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.lblSWStep.setObjectName(_fromUtf8("lblSWStep"))
        self.lblSWDelay = QtGui.QLabel(self.grbSweepParam)
        self.lblSWDelay.setGeometry(QtCore.QRect(180, 90, 61, 16))
        self.lblSWDelay.setObjectName(_fromUtf8("lblSWDelay"))
        self.ledtBias = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtBias.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.ledtBias.setObjectName(_fromUtf8("ledtBias"))
        self.ledtStart = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtStart.setGeometry(QtCore.QRect(70, 60, 81, 20))
        self.ledtStart.setObjectName(_fromUtf8("ledtStart"))
        self.ledtStop = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtStop.setGeometry(QtCore.QRect(250, 60, 81, 20))
        self.ledtStop.setObjectName(_fromUtf8("ledtStop"))
        self.ledtStep = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtStep.setGeometry(QtCore.QRect(70, 90, 81, 20))
        self.ledtStep.setObjectName(_fromUtf8("ledtStep"))
        self.ledtDelay = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtDelay.setGeometry(QtCore.QRect(250, 90, 81, 20))
        self.ledtDelay.setObjectName(_fromUtf8("ledtDelay"))
        self.ledtCounts = QtGui.QLineEdit(self.grbSweepParam)
        self.ledtCounts.setGeometry(QtCore.QRect(70, 120, 81, 20))
        self.ledtCounts.setObjectName(_fromUtf8("ledtCounts"))
        self.lblSWCounts = QtGui.QLabel(self.grbSweepParam)
        self.lblSWCounts.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.lblSWCounts.setObjectName(_fromUtf8("lblSWCounts"))
        self.lblSWLogPPD = QtGui.QLabel(self.grbSweepParam)
        self.lblSWLogPPD.setGeometry(QtCore.QRect(180, 120, 46, 13))
        self.lblSWLogPPD.setObjectName(_fromUtf8("lblSWLogPPD"))
        self.cboxSWLogPPD = QtGui.QComboBox(self.grbSweepParam)
        self.cboxSWLogPPD.setGeometry(QtCore.QRect(250, 120, 69, 22))
        self.cboxSWLogPPD.setObjectName(_fromUtf8("cboxSWLogPPD"))
        self.cboxSWLogPPD.addItem(_fromUtf8(""))
        self.cboxSWLogPPD.addItem(_fromUtf8(""))
        self.cboxSWLogPPD.addItem(_fromUtf8(""))
        self.cboxSWLogPPD.addItem(_fromUtf8(""))
        self.cboxSWBiasRange = QtGui.QComboBox(self.grbSweepParam)
        self.cboxSWBiasRange.setGeometry(QtCore.QRect(250, 30, 69, 22))
        self.cboxSWBiasRange.setEditable(False)
        self.cboxSWBiasRange.setMaxCount(10)
        self.cboxSWBiasRange.setMinimumContentsLength(5)
        self.cboxSWBiasRange.setObjectName(_fromUtf8("cboxSWBiasRange"))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.cboxSWBiasRange.addItem(_fromUtf8(""))
        self.grbComp = QtGui.QGroupBox(self.centralwidget)
        self.grbComp.setGeometry(QtCore.QRect(20, 130, 171, 141))
        self.grbComp.setObjectName(_fromUtf8("grbComp"))
        self.lblComp = QtGui.QLabel(self.grbComp)
        self.lblComp.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.lblComp.setObjectName(_fromUtf8("lblComp"))
        self.btnComp = QtGui.QPushButton(self.grbComp)
        self.btnComp.setGeometry(QtCore.QRect(40, 110, 91, 23))
        self.btnComp.setObjectName(_fromUtf8("btnComp"))
        self.lblCompRange = QtGui.QLabel(self.grbComp)
        self.lblCompRange.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.lblCompRange.setObjectName(_fromUtf8("lblCompRange"))
        self.ledtComp = QtGui.QLineEdit(self.grbComp)
        self.ledtComp.setGeometry(QtCore.QRect(90, 20, 71, 20))
        self.ledtComp.setObjectName(_fromUtf8("ledtComp"))
        self.cboxCompRange = QtGui.QComboBox(self.grbComp)
        self.cboxCompRange.setGeometry(QtCore.QRect(90, 60, 69, 22))
        self.cboxCompRange.setMaxCount(10)
        self.cboxCompRange.setObjectName(_fromUtf8("cboxCompRange"))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.cboxCompRange.addItem(_fromUtf8(""))
        self.grbFunction = QtGui.QGroupBox(self.centralwidget)
        self.grbFunction.setGeometry(QtCore.QRect(20, 50, 351, 71))
        self.grbFunction.setObjectName(_fromUtf8("grbFunction"))
        self.rdoSWSourceCurr = QtGui.QRadioButton(self.grbFunction)
        self.rdoSWSourceCurr.setGeometry(QtCore.QRect(20, 40, 141, 21))
        self.rdoSWSourceCurr.setObjectName(_fromUtf8("rdoSWSourceCurr"))
        self.rdoSWSourceVolt = QtGui.QRadioButton(self.grbFunction)
        self.rdoSWSourceVolt.setGeometry(QtCore.QRect(190, 40, 141, 21))
        self.rdoSWSourceVolt.setObjectName(_fromUtf8("rdoSWSourceVolt"))
        self.rdoDCSourceCurr = QtGui.QRadioButton(self.grbFunction)
        self.rdoDCSourceCurr.setGeometry(QtCore.QRect(20, 20, 141, 17))
        self.rdoDCSourceCurr.setObjectName(_fromUtf8("rdoDCSourceCurr"))
        self.rdoDCSourceVolt = QtGui.QRadioButton(self.grbFunction)
        self.rdoDCSourceVolt.setGeometry(QtCore.QRect(190, 20, 141, 17))
        self.rdoDCSourceVolt.setObjectName(_fromUtf8("rdoDCSourceVolt"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(379, 10, 421, 301))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.lblTitle = QtGui.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(20, 10, 191, 31))
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.btnSweep = QtGui.QPushButton(self.centralwidget)
        self.btnSweep.setGeometry(QtCore.QRect(380, 460, 101, 31))
        self.btnSweep.setObjectName(_fromUtf8("btnSweep"))
        self.btnTrigger = QtGui.QPushButton(self.centralwidget)
        self.btnTrigger.setGeometry(QtCore.QRect(600, 460, 101, 31))
        self.btnTrigger.setObjectName(_fromUtf8("btnTrigger"))
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(720, 430, 91, 61))
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.btnOperate = QtGui.QPushButton(self.centralwidget)
        self.btnOperate.setGeometry(QtCore.QRect(490, 460, 101, 31))
        self.btnOperate.setObjectName(_fromUtf8("btnOperate"))
        self.grbDCBias = QtGui.QGroupBox(self.centralwidget)
        self.grbDCBias.setGeometry(QtCore.QRect(200, 130, 171, 141))
        self.grbDCBias.setObjectName(_fromUtf8("grbDCBias"))
        self.btnDCBias = QtGui.QPushButton(self.grbDCBias)
        self.btnDCBias.setGeometry(QtCore.QRect(40, 110, 91, 23))
        self.btnDCBias.setObjectName(_fromUtf8("btnDCBias"))
        self.ledtDCDelay = QtGui.QLineEdit(self.grbDCBias)
        self.ledtDCDelay.setGeometry(QtCore.QRect(80, 80, 71, 20))
        self.ledtDCDelay.setObjectName(_fromUtf8("ledtDCDelay"))
        self.lblBiasRange = QtGui.QLabel(self.grbDCBias)
        self.lblBiasRange.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.lblBiasRange.setObjectName(_fromUtf8("lblBiasRange"))
        self.ledtDCBias = QtGui.QLineEdit(self.grbDCBias)
        self.ledtDCBias.setGeometry(QtCore.QRect(80, 20, 71, 20))
        self.ledtDCBias.setObjectName(_fromUtf8("ledtDCBias"))
        self.cboxDCBiasRange = QtGui.QComboBox(self.grbDCBias)
        self.cboxDCBiasRange.setGeometry(QtCore.QRect(80, 50, 69, 22))
        self.cboxDCBiasRange.setEditable(False)
        self.cboxDCBiasRange.setMaxVisibleItems(10)
        self.cboxDCBiasRange.setMaxCount(10)
        self.cboxDCBiasRange.setMinimumContentsLength(5)
        self.cboxDCBiasRange.setObjectName(_fromUtf8("cboxDCBiasRange"))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.cboxDCBiasRange.addItem(_fromUtf8(""))
        self.lblDCDelay = QtGui.QLabel(self.grbDCBias)
        self.lblDCDelay.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.lblDCDelay.setObjectName(_fromUtf8("lblDCDelay"))
        self.lblBias = QtGui.QLabel(self.grbDCBias)
        self.lblBias.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.lblBias.setObjectName(_fromUtf8("lblBias"))
        self.grbFile = QtGui.QGroupBox(self.centralwidget)
        self.grbFile.setGeometry(QtCore.QRect(380, 320, 421, 51))
        self.grbFile.setObjectName(_fromUtf8("grbFile"))
        self.btnFileDialog = QtGui.QPushButton(self.grbFile)
        self.btnFileDialog.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.btnFileDialog.setObjectName(_fromUtf8("btnFileDialog"))
        self.ledtFile = QtGui.QLineEdit(self.grbFile)
        self.ledtFile.setGeometry(QtCore.QRect(90, 20, 241, 20))
        self.ledtFile.setObjectName(_fromUtf8("ledtFile"))
        self.chboxSaveOnOff = QtGui.QCheckBox(self.grbFile)
        self.chboxSaveOnOff.setGeometry(QtCore.QRect(340, 20, 81, 17))
        self.chboxSaveOnOff.setObjectName(_fromUtf8("chboxSaveOnOff"))
        self.grbSenseSet = QtGui.QGroupBox(self.centralwidget)
        self.grbSenseSet.setGeometry(QtCore.QRect(380, 380, 131, 71))
        self.grbSenseSet.setObjectName(_fromUtf8("grbSenseSet"))
        self.rdoRemoteSense = QtGui.QRadioButton(self.grbSenseSet)
        self.rdoRemoteSense.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rdoRemoteSense.setObjectName(_fromUtf8("rdoRemoteSense"))
        self.rdoLocalSense = QtGui.QRadioButton(self.grbSenseSet)
        self.rdoLocalSense.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rdoLocalSense.setObjectName(_fromUtf8("rdoLocalSense"))
        keithleyOnlyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(keithleyOnlyWindow)
        self.cboxSWBiasRange.setCurrentIndex(0)
        self.cboxDCBiasRange.setCurrentIndex(0)
        QtCore.QObject.connect(self.rdoDC, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtStart.setDisabled)
        QtCore.QObject.connect(self.rdoDC, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtStop.setDisabled)
        QtCore.QObject.connect(self.rdoDC, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtStep.setDisabled)
        QtCore.QObject.connect(self.rdoLinear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtCounts.setDisabled)
        QtCore.QObject.connect(self.rdoLog, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtStep.setDisabled)
        QtCore.QObject.connect(self.rdoLog, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtBias.setDisabled)
        QtCore.QObject.connect(self.rdoLinear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtBias.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceCurr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbSweepParam.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceVolt, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbSweepParam.setDisabled)
        QtCore.QObject.connect(self.rdoLog, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtCounts.setDisabled)
        QtCore.QObject.connect(self.rdoLinear, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cboxSWLogPPD.setDisabled)
        QtCore.QObject.connect(self.rdoDC, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cboxSWLogPPD.setDisabled)
        QtCore.QObject.connect(self.rdoSWSourceCurr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ledtDCBias.setDisabled)
        QtCore.QObject.connect(self.rdoSWSourceCurr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbDCBias.setDisabled)
        QtCore.QObject.connect(self.rdoSWSourceVolt, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbDCBias.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceCurr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbSweepType.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceVolt, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.grbSweepType.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceCurr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnSweep.setDisabled)
        QtCore.QObject.connect(self.rdoDCSourceVolt, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnSweep.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(keithleyOnlyWindow)

    def retranslateUi(self, keithleyOnlyWindow):
        keithleyOnlyWindow.setWindowTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Keithley 238 Source-Measure Unit Control", None, QtGui.QApplication.UnicodeUTF8))
        self.grbSweepType.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Sweep Type", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLinear.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Linear Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLog.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Logarithmic Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoDC.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "DC Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.grbSweepParam.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Sweep Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWBias.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Bias Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWBiasRange.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Bias Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWStart.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWStop.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Stop:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWStep.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWDelay.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Delay (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtBias.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtStart.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "-1E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtStop.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "1E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtStep.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "1E-10", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtDelay.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtCounts.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWCounts.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Counts:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSWLogPPD.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "PPD:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWLogPPD.setItemText(0, QtGui.QApplication.translate("keithleyOnlyWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWLogPPD.setItemText(1, QtGui.QApplication.translate("keithleyOnlyWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWLogPPD.setItemText(2, QtGui.QApplication.translate("keithleyOnlyWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWLogPPD.setItemText(3, QtGui.QApplication.translate("keithleyOnlyWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(0, QtGui.QApplication.translate("keithleyOnlyWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(1, QtGui.QApplication.translate("keithleyOnlyWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(2, QtGui.QApplication.translate("keithleyOnlyWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(3, QtGui.QApplication.translate("keithleyOnlyWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(4, QtGui.QApplication.translate("keithleyOnlyWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(5, QtGui.QApplication.translate("keithleyOnlyWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(6, QtGui.QApplication.translate("keithleyOnlyWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(7, QtGui.QApplication.translate("keithleyOnlyWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(8, QtGui.QApplication.translate("keithleyOnlyWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxSWBiasRange.setItemText(9, QtGui.QApplication.translate("keithleyOnlyWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.grbComp.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Compliance Level", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComp.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Compliance:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnComp.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Set Compliance", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCompRange.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Comp. Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtComp.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "5.000", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(0, QtGui.QApplication.translate("keithleyOnlyWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(1, QtGui.QApplication.translate("keithleyOnlyWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(2, QtGui.QApplication.translate("keithleyOnlyWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(3, QtGui.QApplication.translate("keithleyOnlyWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(4, QtGui.QApplication.translate("keithleyOnlyWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(5, QtGui.QApplication.translate("keithleyOnlyWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(6, QtGui.QApplication.translate("keithleyOnlyWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(7, QtGui.QApplication.translate("keithleyOnlyWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(8, QtGui.QApplication.translate("keithleyOnlyWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxCompRange.setItemText(9, QtGui.QApplication.translate("keithleyOnlyWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.grbFunction.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Sweep Function", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSWSourceCurr.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "SW Source I, Measure V", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSWSourceVolt.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "SW Source V, Measure I", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoDCSourceCurr.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "DC Source I, Measrue V", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoDCSourceVolt.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "DC Source V, Measure I", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitle.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "<html><head/><body><p><span style=\" font-size:18pt; text-decoration: underline;\">Keithley 238 SMU</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSweep.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Set Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTrigger.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Trigger Now", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "STOP/\n"
"Operate Off", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOperate.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Operate ON", None, QtGui.QApplication.UnicodeUTF8))
        self.grbDCBias.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Bias Level (Non-sweep)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDCBias.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Set Bias", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtDCDelay.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBiasRange.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Bias Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtDCBias.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "1E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(0, QtGui.QApplication.translate("keithleyOnlyWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(1, QtGui.QApplication.translate("keithleyOnlyWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(2, QtGui.QApplication.translate("keithleyOnlyWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(3, QtGui.QApplication.translate("keithleyOnlyWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(4, QtGui.QApplication.translate("keithleyOnlyWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(5, QtGui.QApplication.translate("keithleyOnlyWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(6, QtGui.QApplication.translate("keithleyOnlyWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(7, QtGui.QApplication.translate("keithleyOnlyWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(8, QtGui.QApplication.translate("keithleyOnlyWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cboxDCBiasRange.setItemText(9, QtGui.QApplication.translate("keithleyOnlyWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDCDelay.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Delay (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBias.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Bias:", None, QtGui.QApplication.UnicodeUTF8))
        self.grbFile.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Save to File:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileDialog.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.ledtFile.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "C:\\Users\\Josh\\Desktop\\testK288data.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.chboxSaveOnOff.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Save Data?", None, QtGui.QApplication.UnicodeUTF8))
        self.grbSenseSet.setTitle(QtGui.QApplication.translate("keithleyOnlyWindow", "Local / Remote Sense", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoRemoteSense.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLocalSense.setText(QtGui.QApplication.translate("keithleyOnlyWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
